### ISSUE TITLE
Suggestion: Ablility to add scripts

### ISSUE THREAD

**Issue by m4x10187** [DS-Homebrew/GodMode9i#232] opened 2023-11-04 20:14 UTC
The 3DS version of GodMode9 has scripts to perform maintenance to the NAND, read/write files directly, amongst other things. It would've been nice if GodMode9i had the same treatment, as this could benefit people.

**Comment by Peter0x44** [comment] 2023-11-04 21:23
I don't see this ever getting implemented, writing to the nand on the DSi is quite risky, and there is generally extremely little reason to do so.
You could irrecoverably brick quite easily.

What need do you have for this feature?

**Comment by R-YaTian** [comment] 2024-01-03 01:10
Duplicate of #49

**Closed** 2024-01-03 01:12 UTC
